"""
Configuration Facade for the All-in-One Discord Bot.
Re-exports from config.settings and config.permissions for seamless backwards compatibility.
"""

from __future__ import annotations

from config.settings import (
    BASE_DIR,
    DATA_DIR,
    BACKUPS_DIR,
    LOGS_DIR,
    CACHE_DIR,
    TRANSCRIPTS_DIR,
    TEMP_DIR,
    ENV_PATH,
    DISCORD_TOKEN,
    BOT_PREFIX,
    BOT_VERSION,
    LOG_LEVEL_STR,
    DATABASE_PATH,
    DATABASE_URL,
    COMMAND_SYNC_MODE,
    TEST_GUILD_ID,
    LAVALINK_HOST,
    LAVALINK_PORT,
    LAVALINK_PASSWORD,
    LAVALINK_ENABLED,
    MAX_QUEUE_SIZE,
    MAX_SAVED_PLAYLISTS_PER_USER,
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_RESET_TIMEOUT,
    Colors,
    WEB_PORT,
    DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET,
    DISCORD_REDIRECT_URI,
    SESSION_SECRET,
    COMMUNITY_GUILD_ID,
    MUSIC_DUPLICATE_REQUEST_WINDOW_SECONDS,
    MUSIC_USER_RATE_LIMIT_COUNT,
    MUSIC_USER_RATE_LIMIT_WINDOW,
    get_log_level,
    is_token_valid,
    get_masked_token,
)

from config.permissions import (
    PermissionLevel,
    FOUNDER_ROLE_ID,
    BOT_USER_ID,
    get_member_permission_level,
    has_permission,
    is_founder_or_owner,
    is_admin_or_owner,
    is_guild_owner,
    is_dj_or_staff,
    can_moderate,
    check_bot_hierarchy,
)

__all__ = [
    "BASE_DIR",
    "DATA_DIR",
    "BACKUPS_DIR",
    "LOGS_DIR",
    "CACHE_DIR",
    "TRANSCRIPTS_DIR",
    "TEMP_DIR",
    "ENV_PATH",
    "DISCORD_TOKEN",
    "BOT_PREFIX",
    "BOT_VERSION",
    "LOG_LEVEL_STR",
    "DATABASE_PATH",
    "DATABASE_URL",
    "COMMAND_SYNC_MODE",
    "TEST_GUILD_ID",
    "LAVALINK_HOST",
    "LAVALINK_PORT",
    "LAVALINK_PASSWORD",
    "LAVALINK_ENABLED",
    "MAX_QUEUE_SIZE",
    "MAX_SAVED_PLAYLISTS_PER_USER",
    "CIRCUIT_BREAKER_FAILURE_THRESHOLD",
    "CIRCUIT_BREAKER_RESET_TIMEOUT",
    "Colors",
    "get_log_level",
    "is_token_valid",
    "get_masked_token",
    "PermissionLevel",
    "FOUNDER_ROLE_ID",
    "BOT_USER_ID",
    "get_member_permission_level",
    "has_permission",
    "is_founder_or_owner",
    "is_admin_or_owner",
    "is_guild_owner",
    "is_dj_or_staff",
    "can_moderate",
    "check_bot_hierarchy",
]
