"""
Production Observability, Monitoring & Disaster Telemetry Layer for 『RΛI』.
Provides Prometheus metrics, health evaluation matrix, Sentry crash reporting with sanitization,
and Grafana dashboard generators.
"""

from observability.health import ObservabilityHealthService, SystemHealthReport
from observability.metrics import (
    MetricsServer,
    rai_security_events_total,
    rai_security_incidents_total,
    rai_security_incidents_active,
    rai_raid_detections_total,
    rai_antinuke_events_total,
    rai_antispam_events_total,
    rai_mass_mention_events_total,
    rai_security_actions_total,
    rai_security_actions_failed_total,
    rai_emergency_mode_active,
    rai_discord_events_total,
    rai_discord_api_errors_total,
    rai_discord_rate_limits_total,
    rai_discord_command_total,
    rai_discord_event_latency_seconds,
    rai_sqlite_operations_total,
    rai_postgres_operations_total,
    rai_redis_operations_total,
    rai_firebase_operations_total,
    rai_sync_queue_size,
    rai_sync_operations_total,
    rai_sync_dead_letter_total,
    rai_worker_health,
    rai_worker_restarts_total,
    rai_music_sessions,
    rai_ai_requests_total,
    rai_ai_latency_seconds,
)
from observability.sentry_tracker import SentryTracker, sanitize_text, sanitize_dict
from observability.dashboards import generate_grafana_dashboard, export_grafana_dashboard

__all__ = [
    "ObservabilityHealthService",
    "SystemHealthReport",
    "MetricsServer",
    "SentryTracker",
    "sanitize_text",
    "sanitize_dict",
    "generate_grafana_dashboard",
    "export_grafana_dashboard",
    "rai_security_events_total",
    "rai_security_incidents_total",
    "rai_security_incidents_active",
    "rai_raid_detections_total",
    "rai_antinuke_events_total",
    "rai_antispam_events_total",
    "rai_mass_mention_events_total",
    "rai_security_actions_total",
    "rai_security_actions_failed_total",
    "rai_emergency_mode_active",
    "rai_discord_events_total",
    "rai_discord_api_errors_total",
    "rai_discord_rate_limits_total",
    "rai_discord_command_total",
    "rai_discord_event_latency_seconds",
    "rai_sqlite_operations_total",
    "rai_postgres_operations_total",
    "rai_redis_operations_total",
    "rai_firebase_operations_total",
    "rai_sync_queue_size",
    "rai_sync_operations_total",
    "rai_sync_dead_letter_total",
    "rai_worker_health",
    "rai_worker_restarts_total",
    "rai_music_sessions",
    "rai_ai_requests_total",
    "rai_ai_latency_seconds",
]
