"""
Configuration package for Rai.
Exports settings and permissions.
"""

from config.settings import (
    BASE_DIR,
    DATA_DIR,
    BACKUPS_DIR,
    LOGS_DIR,
    CACHE_DIR,
    TRANSCRIPTS_DIR,
    TEMP_DIR,
    ENV_PATH,
    DISCORD_TOKEN,
    BOT_PREFIX,
    BOT_VERSION,
    LOG_LEVEL_STR,
    DATABASE_PATH,
    COMMAND_SYNC_MODE,
    TEST_GUILD_ID,
    Colors,
    WEB_PORT,
    DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET,
    DISCORD_REDIRECT_URI,
    SESSION_SECRET,
    COMMUNITY_GUILD_ID,
    get_log_level,
    is_token_valid,
    get_masked_token,
)

from config.permissions import (
    PermissionLevel,
    FOUNDER_ROLE_ID,
    BOT_USER_ID,
    get_member_permission_level,
    has_permission,
    is_founder_or_owner,
    is_admin_or_owner,
    is_guild_owner,
    is_dj_or_staff,
    can_moderate,
    check_bot_hierarchy,
)

__all__ = [
    "BASE_DIR",
    "DATA_DIR",
    "BACKUPS_DIR",
    "LOGS_DIR",
    "CACHE_DIR",
    "TRANSCRIPTS_DIR",
    "TEMP_DIR",
    "ENV_PATH",
    "DISCORD_TOKEN",
    "BOT_PREFIX",
    "BOT_VERSION",
    "LOG_LEVEL_STR",
    "DATABASE_PATH",
    "COMMAND_SYNC_MODE",
    "TEST_GUILD_ID",
    "Colors",
    "get_log_level",
    "is_token_valid",
    "get_masked_token",
    "PermissionLevel",
    "FOUNDER_ROLE_ID",
    "BOT_USER_ID",
    "get_member_permission_level",
    "has_permission",
    "is_founder_or_owner",
    "is_admin_or_owner",
    "is_guild_owner",
    "is_dj_or_staff",
    "can_moderate",
    "check_bot_hierarchy",
]
